#!/bin/sh

## hyphop ##

NOW=`TZ='UTC' date` ../tools/md2html \
    README.md \
    index.html

wkhtmltopdf index.html Anna_Belimova_CV.pdf

#../tools/html2pdf index.html Anna_Belimova_CV.pdf
#../tools/html2pdf2 index.html Anna_Belimova_CV.pdf
